version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    command: /api/scriptfiles/dev/build.sh
    restart: always
    env_file:
      - ./.env
    ports:
      - '8000:8000'
      - '8001:8001'
    depends_on:
      - db
      - redis
    volumes:
      - .:/api

  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/local.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles/:/api/static
      - ./media/:/api/media
    depends_on:
      - api

  redis:
    image: redis:latest
    container_name: redis
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "5432:5432"
