# CircleCI configuration file
version: 2.1

executors:
  backend-executor:
    docker:
      - image: cimg/python:3.10
      - image: cimg/redis:7.0
      - image: cimg/postgres:15.0
        environment:
          POSTGRES_DB: testdb
          POSTGRES_USER: circleci
          POSTGRES_PASSWORD: circleci

jobs:
  # Job one with a unique name
  check-lint:
    executor: backend-executor
    steps:
      - checkout
      - run:
          name: Install Lint packages
          command: |
            pip install flake8
      - run:
          name: Check Lint
          command: |
            flake8 .

  test-backend:
    executor: backend-executor
    environment:
      DEBUG: 1
      DB_ENGINE: postgresql
      DB_NAME: testdb
      DB_USER: circleci
      DB_PASSWORD: circleci
      DB_HOST: localhost
      DB_PORT: 5432
      ENVIRONMENT: development
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install postgresql-client
            pip install -r requirements.txt
            pip install coverage
            pip install pytest-django
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.6.1
      - run:
          name: Wait for db and migrate
          command: |
            dockerize -wait tcp://$DB_HOST:$DB_PORT -timeout 1m
            python manage.py migrate
      - run:
          name: Run unit test
          command: |
            coverage run -m pytest --junitxml=test-results/junit.xml
            coverage html
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: htmlcov

  deploy-prod:
    docker:
    # specify the version you desire here (you might not want node)
    - image: circleci/node:7.10
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "59:49:79:51:6d:cc:b8:d1:17:b6:2f:af:cd:ea:12:15"
      - run: ssh $DROPLET_USER@$DROPLET_IP "./deploy-v2.sh"

workflows:
  # Name of workflow
  pipeline:
    # List of jobs that will run
    jobs:
      - check-lint
      - test-backend
      - deploy-prod:
          requires:
            - test-backend
            - check-lint
          filters:
            branches:
              only:
                - main
